const cardContent = [
    {
        id: 1,
        location: 'Toronto',
        cardTitleChip: 'Environment',
        image: 'src/assets/blog_img_2018-11-09_11-14-55_Y1HyDbI6XseN3pLj.jpg',
        title: 'Grow Trees - On the path to environment sustainability',
        description: 'Lorem ipsum dolor sit amet, consectetur advising elite, sed do eiusmod tempore incididunt ut labore...',
        company: ' Trees Canada',
        chipLabel: 'From 10/01/2019 until 25/02/2019',
        seats: '10',
        seatsTitle: 'Seats Left',
        date: '09/01/2019',
        dateTitle: ' Deadline',
    },
    {
        id: 2,
        location: 'Melbourne',
        cardTitleChip: 'Children',
        image: 'src/assets/download.jpeg',
        title: 'Education Supplies for Every Pair of Shoes Sold',
        description: 'Lorem ipsum dolor sit amet, consectetur advising elite, sed do eiusmod tempore incididunt ut labore...',
        company: 'Australian Paradise',
        chipLabel: 'From 10/01/2019 until 25/02/2019',
        seats: '250',
        seatsTitle: 'Already volunteered',
        date: '09/01/2019',
        dateTitle: ' Deadline',
    },
    {
        id: 3,
        location: 'Barcelona',
        cardTitleChip: 'Nutrition',
        image: 'src/assets/blog_img_2018-11-09_11-14-55_Y1HyDbI6XseN3pLj.jpg',
        title: 'Nourish the Children in African country',
        description: 'Lorem ipsum dolor sit amet, consectetur advising elite, sed do eiusmod tempore incididunt ut labore...',
        company: 'The Hunger',
        chipLabel: 'Ongoing Opportunity',
        seats: '10',
        seatsTitle: ' Seats left',
        date: '09/01/2019',
        dateTitle: ' Deadline',
    },
    {
        id: 4,
        location: 'London',
        cardTitleChip: 'Environment',
        image: 'src/assets/blog_img_2018-11-09_11-14-55_Y1HyDbI6XseN3pLj.jpg',
        title: 'CSR initiative stands for Coffee and Farmer Equity',
        description: 'Lorem ipsum dolor sit amet, consectetur advising elite, sed do eiusmod tempore incididunt ut labore...',
        company: 'CSE Network',
        chipLabel: 'Ongoing Opportunity',
        seats: '250',
        seatsTitle: ' Already volunteered',
    },
    {
        id: 5,
        location: 'Cape Town',
        image: 'src/assets/blog_img_2018-11-09_11-14-55_Y1HyDbI6XseN3pLj.jpg',
        cardTitleChip: 'Animals',
        title: 'Animal welfare & save birds campaign',
        description: 'Lorem ipsum dolor sit amet, consectetur advising elite, sed do eiusmod tempore incididunt ut labore...',
        company: 'JR Foundation',
        chipLabel: 'Plant 10,000 Trees',
        seats: '10',
        seatsTitle: ' Already volunteered',
        type: 'range',
        rangeTitle: '8000 achieved'
    },
    {
        id: 6,
        location: 'Education',
        image: 'src/assets/blog_img_2018-11-09_11-14-55_Y1HyDbI6XseN3pLj.jpg',
        cardTitleChip: 'Health',
        title: 'Grow Trees – On the path to environment sustainability',
        description: 'Lorem ipsum dolor sit amet, consectetur advising elite, sed do eiusmod tempore incididunt ut labore...',
        company: 'Tree Canada',
        chipLabel: 'Ongoing Opportunity',

    },
    {
        id: 7,
        location: 'Sydney',
        cardTitleChip: 'Children',
        image: 'src/assets/blog_img_2018-11-09_11-14-55_Y1HyDbI6XseN3pLj.jpg',
        title: 'Education Supplies for Every Pair of Shoes Sold',
        description: 'Lorem ipsum dolor sit amet, consectetur advising elite, sed do eiusmod tempore incididunt ut labore...',
        company: 'Australian Paradise',
        chipLabel: 'From 10/01/2019 until 25/02/2019',
        seats: '250',
        seatsTitle: 'Already volunteered',
        date: '09/01/2019',
        dateTitle: ' Deadline',
    },
    {
        id: 8,
        location: 'Barcelona',
        cardTitleChip: 'Nutrition',
        image: 'src/assets/blog_img_2018-11-09_11-14-55_Y1HyDbI6XseN3pLj.jpg',
        title: 'Nourish the Children in African country',
        description: 'Lorem ipsum dolor sit amet, consectetur advising elite, sed do eiusmod tempore incididunt ut labore...',
        company: 'The Hunger',
        chipLabel: 'Ongoing Opportunity',
        seats: '10',
        seatsTitle: ' Seats left',
        date: '09/01/2019',
        dateTitle: ' Deadline',
    },
    {
        id: 9,
        location: 'Paris',
        cardTitleChip: 'Nutrition',
        image: 'src/assets/blog_img_2018-11-09_11-14-55_Y1HyDbI6XseN3pLj.jpg',
        title: 'Plantation and Afforestation programme',
        description: 'Lorem ipsum dolor sit amet, consectetur advising elite, sed do eiusmod tempore incididunt ut labore...',
        company: 'Amaze Doctors',
        chipLabel: 'Plant 10,000 Trees',
        type: 'range',
        rangeTitle: '8000 achieved'
    },
]

export default cardContent;